"""Type stubs for sonara — high-performance audio analysis."""

from typing import Dict, List, Optional, Tuple, Union
import numpy as np
from numpy.typing import NDArray

# Type aliases
AudioArray = NDArray[np.float64]
SpectrogramArray = NDArray[np.float64]
ComplexArray = NDArray[np.complex128]

# ============================================================
# Core: Audio I/O
# ============================================================

def load(path: str, *, sr: int = 22050, mono: bool = True, offset: float = 0.0, duration: float = 0.0) -> Tuple[AudioArray, int]: ...
def to_mono(y: NDArray[np.float64]) -> AudioArray: ...
def resample(y: AudioArray, *, orig_sr: int, target_sr: int) -> AudioArray: ...
def get_duration(path: str) -> float: ...
def get_samplerate(path: str) -> int: ...
def autocorrelate(y: AudioArray, *, max_size: Optional[int] = None) -> AudioArray: ...
def lpc(y: AudioArray, *, order: int) -> AudioArray: ...
def zero_crossings(y: AudioArray, *, threshold: float = 0.0) -> NDArray[np.bool_]: ...
def tone(frequency: float, *, sr: int = 22050, length: int = 22050) -> AudioArray: ...
def chirp(*, fmin: float, fmax: float, sr: int = 22050, length: int = 22050) -> AudioArray: ...
def clicks(*, times: List[float], sr: int = 22050, length: int = 22050, click_freq: float = 1000.0, click_duration: float = 0.1) -> AudioArray: ...
def mu_compress(x: AudioArray, *, mu: float = 255.0) -> AudioArray: ...
def mu_expand(y: AudioArray, *, mu: float = 255.0) -> AudioArray: ...

# ============================================================
# Core: Spectrum
# ============================================================

def stft(y: AudioArray, *, n_fft: int = 2048, hop_length: Optional[int] = None, win_length: Optional[int] = None, window: str = "hann", center: bool = True, pad_mode: str = "constant") -> ComplexArray: ...
def istft(stft_matrix: ComplexArray, *, hop_length: Optional[int] = None, win_length: Optional[int] = None, window: str = "hann", center: bool = True, length: Optional[int] = None) -> AudioArray: ...
def magphase(d: ComplexArray, *, power: float = 1.0) -> Tuple[SpectrogramArray, ComplexArray]: ...
def phase_vocoder(d: ComplexArray, *, rate: float, hop_length: Optional[int] = None) -> ComplexArray: ...
def power_to_db(s: SpectrogramArray, *, ref_power: float = 1.0, amin: float = 1e-10, top_db: float = 80.0) -> SpectrogramArray: ...
def db_to_power(s_db: SpectrogramArray, *, ref_power: float = 1.0) -> SpectrogramArray: ...
def amplitude_to_db(s: SpectrogramArray, *, ref_amplitude: float = 1.0, amin: float = 1e-5, top_db: float = 80.0) -> SpectrogramArray: ...
def db_to_amplitude(s_db: SpectrogramArray, *, ref_amplitude: float = 1.0) -> SpectrogramArray: ...
def griffinlim(s_mag: SpectrogramArray, *, n_iter: int = 32, hop_length: Optional[int] = None, win_length: Optional[int] = None, window: str = "hann") -> AudioArray: ...
def pcen(s: SpectrogramArray, *, sr: float = 22050.0, hop_length: int = 512, gain: float = 0.98, bias: float = 2.0, power: float = 0.5, time_constant: float = 0.06, eps: float = 1e-6) -> SpectrogramArray: ...
def perceptual_weighting(s: SpectrogramArray, frequencies: NDArray[np.float64], *, kind: str = "A") -> SpectrogramArray: ...

# ============================================================
# Core: CQT
# ============================================================

def cqt(y: AudioArray, *, sr: int = 22050, hop_length: int = 512, fmin: Optional[float] = None, n_bins: int = 84, bins_per_octave: int = 12, filter_scale: float = 1.0) -> ComplexArray: ...
def vqt(y: AudioArray, *, sr: int = 22050, hop_length: int = 512, fmin: Optional[float] = None, n_bins: int = 84, bins_per_octave: int = 12, filter_scale: float = 1.0, gamma: float = 0.0) -> ComplexArray: ...
def hybrid_cqt(y: AudioArray, *, sr: int = 22050, hop_length: int = 512, fmin: Optional[float] = None, n_bins: int = 84, bins_per_octave: int = 12, filter_scale: float = 1.0) -> ComplexArray: ...
def pseudo_cqt(y: AudioArray, *, sr: int = 22050, hop_length: int = 512, fmin: Optional[float] = None, n_bins: int = 84, bins_per_octave: int = 12, filter_scale: float = 1.0) -> SpectrogramArray: ...
def icqt(cq: ComplexArray, *, sr: int = 22050, hop_length: int = 512, fmin: Optional[float] = None, bins_per_octave: int = 12, filter_scale: float = 1.0) -> AudioArray: ...
def griffinlim_cqt(cq_mag: SpectrogramArray, *, sr: int = 22050, hop_length: int = 512, fmin: Optional[float] = None, bins_per_octave: int = 12, n_iter: int = 32) -> AudioArray: ...

# ============================================================
# Core: Pitch
# ============================================================

def yin(y: AudioArray, *, fmin: float, fmax: float, sr: int = 22050, frame_length: int = 2048, hop_length: Optional[int] = None, trough_threshold: float = 0.1) -> NDArray[np.float64]: ...
def pyin(y: AudioArray, *, fmin: float, fmax: float, sr: int = 22050, frame_length: int = 2048, hop_length: Optional[int] = None) -> Tuple[NDArray[np.float64], NDArray[np.bool_], NDArray[np.float64]]: ...
def estimate_tuning(*, y: Optional[AudioArray] = None, sr: int = 22050, n_fft: Optional[int] = None, resolution: Optional[float] = None, bins_per_octave: Optional[int] = None) -> float: ...
def pitch_tuning(pitches: List[float], *, resolution: Optional[float] = None, bins_per_octave: Optional[int] = None) -> float: ...
def piptrack(y: AudioArray, *, sr: int = 22050, n_fft: int = 2048, hop_length: Optional[int] = None) -> Tuple[SpectrogramArray, SpectrogramArray]: ...

# ============================================================
# Core: Harmonic
# ============================================================

def salience(s: SpectrogramArray, freqs: NDArray[np.float64], *, harmonics: List[int], weights: Optional[List[float]] = None, fill_value: float = 0.0) -> SpectrogramArray: ...
def interp_harmonics(s: SpectrogramArray, freqs: NDArray[np.float64], *, harmonics: List[float], fill_value: float = 0.0) -> SpectrogramArray: ...
def f0_harmonics(s: SpectrogramArray, freqs: NDArray[np.float64], f0: NDArray[np.float64], *, harmonics: List[float], fill_value: float = 0.0) -> SpectrogramArray: ...

# ============================================================
# Core: Conversions
# ============================================================

def hz_to_mel(freq: float, *, htk: bool = False) -> float: ...
def mel_to_hz(mel: float, *, htk: bool = False) -> float: ...
def hz_to_midi(freq: float) -> float: ...
def midi_to_hz(midi: float) -> float: ...
def note_to_hz(note: str) -> float: ...
def note_to_midi(note: str) -> float: ...
def midi_to_note(midi: float) -> str: ...
def hz_to_note(freq: float) -> str: ...
def hz_to_octs(freq: float, *, tuning: float = 0.0, bins_per_octave: int = 12) -> float: ...
def octs_to_hz(octs: float, *, tuning: float = 0.0, bins_per_octave: int = 12) -> float: ...
def A4_to_tuning(a4: float, *, bins_per_octave: int = 12) -> float: ...
def tuning_to_A4(tuning: float, *, bins_per_octave: int = 12) -> float: ...
def hz_to_svara_h(freq: float, *, sa: float = 261.63, abbr: bool = True) -> str: ...
def hz_to_svara_c(freq: float, *, sa: float = 261.63, abbr: bool = True) -> str: ...
def midi_to_svara_h(midi: float, *, sa: float = 60.0, abbr: bool = True) -> str: ...
def midi_to_svara_c(midi: float, *, sa: float = 60.0, abbr: bool = True) -> str: ...
def note_to_svara_h(note: str, *, sa: str = "C4", abbr: bool = True) -> str: ...
def note_to_svara_c(note: str, *, sa: str = "C4", abbr: bool = True) -> str: ...
def hz_to_fjs(freq: float, *, ref_freq: float = 261.63) -> str: ...
def fft_frequencies(*, sr: float = 22050.0, n_fft: int = 2048) -> NDArray[np.float64]: ...
def mel_frequencies(*, n_mels: int = 128, fmin: float = 0.0, fmax: float = 11025.0, htk: bool = False) -> NDArray[np.float64]: ...
def cqt_frequencies(n_bins: int, *, fmin: float = 32.7032, bins_per_octave: int = 12) -> NDArray[np.float64]: ...
def tempo_frequencies(n_bins: int, *, hop_length: int = 512, sr: float = 22050.0) -> NDArray[np.float64]: ...
def fourier_tempo_frequencies(*, sr: float = 22050.0, win_length: int = 384, hop_length: int = 512) -> NDArray[np.float64]: ...
def frames_to_samples(frames: List[int], *, hop_length: int = 512) -> List[int]: ...
def frames_to_time(frames: List[int], *, sr: float = 22050.0, hop_length: int = 512) -> List[float]: ...
def samples_to_frames(samples: List[int], *, hop_length: int = 512) -> List[int]: ...
def samples_to_time(samples: List[int], *, sr: float = 22050.0) -> List[float]: ...
def time_to_frames(times: List[float], *, sr: float = 22050.0, hop_length: int = 512) -> List[int]: ...
def time_to_samples(times: List[float], *, sr: float = 22050.0) -> List[int]: ...
def blocks_to_frames(blocks: List[int], *, block_length: int, hop_length: int = 512) -> List[int]: ...
def blocks_to_samples(blocks: List[int], *, block_length: int) -> List[int]: ...
def blocks_to_time(blocks: List[int], *, block_length: int, sr: float = 22050.0) -> List[float]: ...
def samples_like(n_frames: int, *, hop_length: int = 512) -> NDArray[np.uintp]: ...
def times_like(n_frames: int, *, sr: float = 22050.0, hop_length: int = 512) -> NDArray[np.float64]: ...

# ============================================================
# Weighting
# ============================================================

def A_weighting(frequencies: NDArray[np.float64]) -> NDArray[np.float64]: ...
def B_weighting(frequencies: NDArray[np.float64]) -> NDArray[np.float64]: ...
def C_weighting(frequencies: NDArray[np.float64]) -> NDArray[np.float64]: ...
def D_weighting(frequencies: NDArray[np.float64]) -> NDArray[np.float64]: ...
def Z_weighting(frequencies: NDArray[np.float64]) -> NDArray[np.float64]: ...
def frequency_weighting(frequencies: NDArray[np.float64], *, kind: str = "A") -> NDArray[np.float64]: ...
def multi_frequency_weighting(frequencies: NDArray[np.float64], kinds: List[str]) -> SpectrogramArray: ...

# ============================================================
# Notation
# ============================================================

def key_to_notes(key: str) -> List[str]: ...
def key_to_degrees(key: str) -> List[int]: ...
def mela_to_degrees(mela: int) -> List[int]: ...
def mela_to_svara(mela: int) -> List[str]: ...
def thaat_to_degrees(thaat: str) -> List[int]: ...
def list_mela() -> List[str]: ...
def list_thaat() -> List[str]: ...
def fifths_to_note(fifths: int) -> str: ...
def interval_to_fjs(interval: float) -> str: ...
def interval_frequencies(n_bins: int, *, fmin: float = 32.7, intervals: List[float], bins_per_octave: int = 12) -> NDArray[np.float64]: ...
def pythagorean_intervals(*, bins_per_octave: int = 12) -> NDArray[np.float64]: ...
def plimit_intervals(*, p: int = 5, bins_per_octave: int = 12) -> NDArray[np.float64]: ...

# ============================================================
# Features
# ============================================================

def melspectrogram(*, y: Optional[AudioArray] = None, S: Optional[SpectrogramArray] = None, sr: float = 22050.0, n_fft: int = 2048, hop_length: int = 512, n_mels: int = 128, fmin: float = 0.0, fmax: float = 0.0, power: float = 2.0) -> SpectrogramArray: ...
def mfcc(*, y: Optional[AudioArray] = None, S: Optional[SpectrogramArray] = None, sr: float = 22050.0, n_mfcc: int = 20, n_fft: int = 2048, hop_length: int = 512, n_mels: int = 128, fmin: float = 0.0, fmax: float = 0.0) -> SpectrogramArray: ...
def chroma_stft(*, y: Optional[AudioArray] = None, S: Optional[SpectrogramArray] = None, sr: float = 22050.0, n_fft: int = 2048, hop_length: int = 512, n_chroma: int = 12, tuning: float = 0.0) -> SpectrogramArray: ...
def spectral_centroid(*, y: Optional[AudioArray] = None, S: Optional[SpectrogramArray] = None, sr: float = 22050.0, n_fft: int = 2048, hop_length: int = 512) -> SpectrogramArray: ...
def rms(*, y: Optional[AudioArray] = None, S: Optional[SpectrogramArray] = None, frame_length: int = 2048, hop_length: int = 512) -> SpectrogramArray: ...

# ============================================================
# Onset / Beat
# ============================================================

def onset_detect(*, y: Optional[AudioArray] = None, onset_envelope: Optional[NDArray[np.float64]] = None, sr: int = 22050, hop_length: int = 512, backtrack: bool = False, delta: float = 0.07, wait: int = 0) -> List[int]: ...
def onset_strength(y: AudioArray, *, sr: int = 22050, hop_length: int = 512) -> NDArray[np.float64]: ...
def beat_track(*, y: Optional[AudioArray] = None, onset_envelope: Optional[NDArray[np.float64]] = None, sr: int = 22050, hop_length: int = 512, start_bpm: float = 120.0, tightness: float = 100.0, trim: bool = True, bpm_min: Optional[float] = None, bpm_max: Optional[float] = None) -> Tuple[float, List[int]]: ...

# ============================================================
# Filters
# ============================================================

def mel(*, sr: float = 22050.0, n_fft: int = 2048, n_mels: int = 128, fmin: float = 0.0, fmax: float = 0.0, htk: bool = False, norm: str = "slaney") -> SpectrogramArray: ...

# ============================================================
# Fused Analysis (sonara-specific, high-performance)
# ============================================================

AnalysisResult = Dict[str, Union[float, int, str, List[int], List[float], List[str], List[Tuple[float, float]]]]

# Result dicts include string fields such as "key" ("A minor"), "key_camelot"
# (Camelot wheel code, e.g. "8A"), "time_signature", and "predominant_chord".
#
# Every result dict carries a "provenance" sub-dict describing how it was
# produced (self-describing time + stale-record detection):
#   provenance: Dict — {
#     "schema_version":     int        # bumped when field meaning/units change
#     "sample_rate":        int        # effective Hz (post-resample); frame
#                                      # indices are valid against this rate
#     "hop_length":         int        # STFT hop of the main pass; seconds =
#                                      # frame * hop_length / sample_rate
#     "mode":               str        # "compact" | "playlist" | "full"
#     "requested_features": List[str]  # sorted; only when features=[...] given
#   }
#
# When chords are computed (playlist/full modes or features=["chords"]), the
# dict also carries typed time-spanned chord events alongside chord_sequence:
#   chord_events: List[Dict]  # {"label": str, "start_sec": float,
#                             #  "end_sec": float} — merged runs of
#                             # chord_sequence; contiguous, covering the track;
#                             # label "N" = no chord detected in that span
def analyze_file(path: str, *, sr: int = 22050, mode: str = "compact", features: Optional[List[str]] = None, bpm_min: Optional[float] = None, bpm_max: Optional[float] = None) -> AnalysisResult: ...
def analyze_signal(y: AudioArray, *, sr: int = 22050, mode: str = "compact", features: Optional[List[str]] = None, bpm_min: Optional[float] = None, bpm_max: Optional[float] = None) -> AnalysisResult: ...
def analyze_batch(paths: List[str], *, sr: int = 22050, mode: str = "compact", features: Optional[List[str]] = None, bpm_min: Optional[float] = None, bpm_max: Optional[float] = None) -> List[AnalysisResult]: ...
# analyze_batch never raises on a per-file decode/IO error. Each input path yields
# exactly one entry in input order, and every entry carries its input `path`.
# A failed file's entry has `path`, `error`, and `error_kind` (e.g. "decode",
# "io", "unsupported_format") instead of feature fields.

# --- beat grid ---
# Opt-in via features=["beatgrid"]. When requested, the analyze_* result dict
# additionally contains:
#   grid_offset_sec: float        — time (sec) of the first beat (grid anchor)
#   downbeats:       List[int]    — frame indices of bar-starting beats
#   grid_stability:  float        — 0..1, how rigidly beats fit a constant grid

# --- structure ---
# Opt-in structural segmentation & energy curve. Requested via
# `features=["structure"]`; absent from every default mode (compact/playlist/
# full). When present, the result dict additionally contains:
#   energy_curve:         List[float]  # per-window perceptual energy (0-1)
#   energy_curve_hop_sec: float        # seconds between curve samples
#   segments:             List[Dict[str, float]]
#                                      # {"start_sec", "end_sec", "energy"}, contiguous, covering
#   intro_end_sec:        float        # end of intro / pre-first-drop region
#   outro_start_sec:      float        # start of outro / final fade
#   energy_level:         int          # coarse 1-10 level
# Extended loudness / gain metrics are opt-in via features=["loudness"] (never
# computed by any mode's defaults, for performance). When requested, the result
# dict also carries:
#   "true_peak_db"                — true peak in dBTP (4x oversampled, ITU-R BS.1770-4)
#   "replaygain_db"               — track gain to reach -18 LUFS (-18 - loudness_lufs)
#   "loudness_curve"              — List[float] short-term LUFS (3 s window, 1 s hop)
#   "loudness_momentary_max_db"   — max momentary (400 ms) loudness, dB
#   "loudness_range_lu"           — EBU R128 loudness range (LRA), LU

# Opt-in analysis keys (present only when requested via `features=[...]`; never
# enabled by any mode). Values are plain Python types in the returned dict:
# --- silence --- features=["silence"]
#   "leading_silence_sec": float   # seconds of leading silence (>= 0, <= duration)
#   "trailing_silence_sec": float  # seconds of trailing silence (>= 0, <= duration)
# --- key candidates --- features=["key_candidates"]
#   "key_candidates": List[Tuple[str, str, float]]  # top-3 (key, camelot, score); [0] == "key"
# --- vocalness --- features=["vocalness"]
#   "vocalness": float             # vocal-presence heuristic in [0, 1] (rough, not a classifier)
# --- mood --- features=["mood"]
#   "mood_happy": float            # heuristic v1, not an ML classifier — in [0, 1]
#   "mood_aggressive": float       # heuristic v1, not an ML classifier — in [0, 1]
#   "mood_relaxed": float          # heuristic v1, not an ML classifier — in [0, 1]
#   "mood_sad": float              # heuristic v1, not an ML classifier — in [0, 1]
#                                  # All four populate together; correlated but not summing to 1.
# --- instrumentalness --- features=["instrumentalness"]
#   "instrumentalness": float      # heuristic v1, not an ML classifier — 1 - vocalness, in [0, 1]
# --- tags --- features=["tags"]  (analyze_file / analyze_batch only)
#   "tags": Dict  # container/stream metadata read from the file; each key present
#                 # only when that tag exists. Keys: "title", "artist", "album",
#                 # "genre" (str), "year", "track_no" (int). Read from
#                 # symphonia containers (FLAC/Vorbis, MP3/ID3v2, MP4, ...); WAV
#                 # (hound fast path) carries no tags. Never set by analyze_signal.
#                 # NOTE: tags["genre"] is the file's metadata genre, distinct
#                 # from the reserved top-level "genre" placeholder.
# ============================================================
# Duplicate detection (acoustic fingerprint) — fingerprint
# ============================================================

# Opt-in only: pass features=["fingerprint"] to any analyze_* call to add two
# fields to the result dict — `fingerprint` (a base64 string) and
# `fingerprint_version` (int). No analysis mode computes them by default.
def fingerprint_match(a: Union[str, Dict], b: Union[str, Dict]) -> float: ...
# Similarity in [0, 1] between two fingerprints, robust to gain / re-encoding /
# small leading-silence differences. Accepts base64 `fingerprint` strings or
# analysis dicts containing one. A score above ~0.30 means "same recording".
def analyze_file(path: str, *, sr: int = 22050) -> Dict[str, Union[float, int, List[int]]]: ...
def analyze_signal(y: AudioArray, *, sr: int = 22050) -> Dict[str, Union[float, int, List[int]]]: ...
def analyze_batch(paths: List[str], *, sr: int = 22050) -> List[Dict[str, Union[float, int, List[int]]]]: ...

# ============================================================
# Similarity & embeddings
# ============================================================
# The similarity vector is OPT-IN: analyze with features=["embedding"] to add
# "embedding" (List[float], EMBEDDING_DIM long) and "embedding_version" (int) to
# the result. It is never produced by a bare mode (compact/playlist/full).

SIMILARITY_VERSION: int
EMBEDDING_DIM: int

def similarity(a: Union[Dict, List[float], NDArray[np.float32]], b: Union[Dict, List[float], NDArray[np.float32]]) -> float: ...
def embedding_distance(a: List[float], b: List[float]) -> float: ...
